### PR TITLE
example R: add the librpma example

### PR DESCRIPTION
**Pull request by ldorau**
In this example we want to introduce to you a basic way of accessing Persistent Memory when it is installed in a remote system. Remote Persistent Memory (or RPMem for short) is a way of doing this via a network by making use of the Remote Direct Memory Access (RDMA) technology.

This example is an introduction to RPMem. We will guide you briefly through setting up all required hardware and software components and verifying whether the connection works properly. Having that, we will show you how to access Persistent Memory on a remote system using the librpma library.

After completing this example you will know:
- what is RPMem and what it is good for,
- how RPMem is different comparing to PMem,
- what hardware and software components are required to start using RPMem,
- how to verify whether the RDMA network works properly,
- how to use librpma API to:
- establish a connection,
- prepare memory for remote manipulation,
- manipulate memory on the remote system,
- assure persistency of stores to the remote system.

Step-by-step you will:
- test the connection on the basic level using ping,
- test the connection RDMA capabilities using rping,
- review an application focusing on establishing a connection,
- review an application reading remote system's memory and writing it back in the persistent manner.

Co-authored-by: Oksana Salyk <oksana.salyk@intel.com>
Co-authored-by: Jan M Michalski <jan.m.michalski@intel.com>
Co-authored-by: Patryk717 <patrykzbierski717@wp.pl>

Signed-off-by: Lukasz Dorau <lukasz.dorau@intel.com>

Ref: https://github.com/pmemhackathon/hackathon/pull/1

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`scripts/enable_pmemusers` line 97 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBTPzX33taiJw42bj0f:-NBTPzX33taiJw42bj0g:bo6ewy3) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/e4ff956b127ca39ddc1d213a04ba0229a97b1bb0/scripts/enable_pmemusers#L97)):*
> ```
> 
> # set name of device DAX
> my $dax_name = "dax0.0";
> ```

My current understanding is that all users will use the same /dev/dax but will map different part of it. However, they can modify the example code and potentially interfere with different users, right?

Wouldn't it be better to to have /dev/dax per user? (Each user would have access to a single dev only, similarly as dirs in create_pmemusers). The machines used for the hackathon are usually fully populated so it should not be a big problem to create a few hundreds of /dev/dax.

I can merge it as it is right now, but I think it could only be used in controlled environment.
___
*[`scripts/enable_pmemusers` line 132 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBTPmKY3KrB-NUfZTwl:-NBTPmKY3KrB-NUfZTwm:b78nupe) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/e4ff956b127ca39ddc1d213a04ba0229a97b1bb0/scripts/enable_pmemusers#L132)):*
> ```
> 
> 	my $ip = `./config_softroce.sh`;
> 	if ($? >> 8) {
> ```

I think the docker command should also be under that if. Otherwise it will fail on `error gathering device information while adding custom device "/dev/infiniband": no such file or directory.`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`scripts/enable_pmemusers` line 132 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBTPmKY3KrB-NUfZTwl:-NBWDbG8-3gWXaHINDnp:b-o419a3) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/e4ff956b127ca39ddc1d213a04ba0229a97b1bb0/scripts/enable_pmemusers#L132)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think the docker command should also be under that if. Otherwise it will fail on `error gathering device information while adding custom device "/dev/infiniband": no such file or directory.`
</blockquote></details>

Right, fixed.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`scripts/enable_pmemusers` line 97 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBTPzX33taiJw42bj0f:-NBWapL03fpTbEpbZSbR:bojpu10) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/e4ff956b127ca39ddc1d213a04ba0229a97b1bb0/scripts/enable_pmemusers#L97)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

My current understanding is that all users will use the same /dev/dax but will map different part of it. However, they can modify the example code and potentially interfere with different users, right?

Wouldn't it be better to to have /dev/dax per user? (Each user would have access to a single dev only, similarly as dirs in create_pmemusers). The machines used for the hackathon are usually fully populated so it should not be a big problem to create a few hundreds of /dev/dax.

I can merge it as it is right now, but I think it could only be used in controlled environment.
</blockquote></details>

I think you are right. It would be better to have a separate DAX device per user. But this is out of scope of this pull request. There are other examples that also use a DAX device, so this issue is an issue of the whole hackathon, not of this example.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)* status: 5 of 8 files reviewed, 16 unresolved discussions (waiting on @igchor, @ldorau, and @lukaszstolarczuk)

___
*[`docker/Dockerfile` line 35 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWs77Q1yfd4MlPfa6v:-NBWs77Q1yfd4MlPfa6w:bo10fyq) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/docker/Dockerfile#L35)):*
> ```Dockerfile
> 	gtest-devel\
> 	hub\
> 	iproute\
> ```

can you please make these new deps as a sep. ENV (like RPMA_DEPS, e.g. https://github.com/pmem/rpma/blob/master/utils/docker/images/Dockerfile.fedora-33#L30)
___
*[`docker/librpma.sh` line 4 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWsIcZ-pFzFr31CCvf:-NBWsIcZ-pFzFr31CCvg:b-r3aoht) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/docker/librpma.sh#L4)):*
> ```Shell
> 
> # 25.08.2022 Merge pull request #2000 from ldorau/common-1.0.0-release
> LIBRPMA_VERSION=1.0.0
> ```

I guess you can bump this to 1.1.0
___
*[`docker/librpma.sh` line 7 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWsZSrA4pG8QLpxxQL:-NBWsZSrA4pG8QLpxxQM:b-pjzi4n) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/docker/librpma.sh#L7)):*
> ```Shell
> ZIP_FILE=rpma.zip
> 
> WORKDIR=$(pwd)
> ```

you can drop this line and just use `pushd <...>` + `popd` (instead of `cd <...>` + `cd <back>`)
___
*[`scripts/config_softroce.sh` line 3 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWt5rs-msGxfvQSdGt:-NBWt5rs-msGxfvQSdGu:b-kms2h0) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/scripts/config_softroce.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020-2021, Intel Corporation
> ```

`-2022`, I guess
___
*[`scripts/enable_pmemusers` line 97 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBTPzX33taiJw42bj0f:-NBWtF137AMbDOAGynFv:b-mypruv) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/e4ff956b127ca39ddc1d213a04ba0229a97b1bb0/scripts/enable_pmemusers#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think you are right. It would be better to have a separate DAX device per user. But this is out of scope of this pull request. There are other examples that also use a DAX device, so this issue is an issue of the whole hackathon, not of this example.
</blockquote></details>

@ldorau, can you please file an issue for that, in this repo...?
___
*[`templates/examples/R/body.tmpl` line 6 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWtpJR-nS5yoCNfxc8:-NBWtpJR-nS5yoCNfxc9:b-o65al5) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L6)):*
> ```
> We assume you already know what Persistent Memory (or PMem for short) is and hopefully
> you have learned many possible ways of benefiting from using it in your applications.
> In this example we want to introduce to you a basic way of accessing the very same
> ```

drop "to you" perhaps (it sounds a little unnatural, for me)
___
*[`templates/examples/R/body.tmpl` line 6 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWtuA4DEow3sK2tH0g:-NBWtuA4DEow3sK2tH0h:bfcmofm) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L6)):*
> ```
> We assume you already know what Persistent Memory (or PMem for short) is and hopefully
> you have learned many possible ways of benefiting from using it in your applications.
> In this example we want to introduce to you a basic way of accessing the very same
> ```

`In this example,` (missing comma)
___
*[`templates/examples/R/body.tmpl` line 7 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWv9s-BzT54zBdfpma:-NBWv9s07ZXed8UanenX:b3o1dbp) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L7)):*
> ```
> you have learned many possible ways of benefiting from using it in your applications.
> In this example we want to introduce to you a basic way of accessing the very same
> Persistent Memory but when it is installed in a remote system. Remote Persistent Memory
> ```

drop `it is`
___
*[`templates/examples/R/body.tmpl` line 15 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWyV7n233h1JaozhZ8:-NBWyV7o5wt0HzJ4uP3G:b-f2hmks) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L15)):*
> ```
> all required hardware and software components and verifying whether the connection
> works properly. Having that, we will show you how to access Persistent Memory
> on a remote system using the librpma library (where RPMA stands for
> ```

`rpma library` or `librpma`
___
*[`templates/examples/R/body.tmpl` line 59 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX-KfED8j7zt9peIz0:-NBX-KfED8j7zt9peIz1:bjpa97b) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L59)):*
> ```
> Alternatively, for development purposes, you can use a software-emulated RDMA network
> interface (SoftRoCE) that can be set up using the following
> <a href="https://github.com/ldorau/2021-04-21.web/blob/devel/scripts/config_softroce.sh" target="_blank">script</a>.
> ```

is this URL correct?
___
*[`templates/examples/R/body.tmpl` line 198 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX38Qv6XeWBGSs_9nl:-NBX38Qv6XeWBGSs_9nm:bimrzbo) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L198)):*
> ```
>     <li>checked the basic network connectivity,</li>
>     <li>checked whether the network is RDMA-capable,</li>
>     <li>established a connection using the librpma library,</li>
> ```

. (lib... library)
___
*[`templates/examples/R/body.tmpl` line 214 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX3efz7Zd2dQccfk3-:-NBX3efz7Zd2dQccfk30:bl8cw71) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L214)):*
> ```
>     </li>
>     <li>RPMem is a way to seamlessly incorporate PMem into modern cloud architectures,</li>
>     <li>the librpma library is a ready-to-use simple API incarnating RPMem principles.</li>
> ```

`incarnating` hmm... I'm not sure if this is a proper word...?
___
*[`templates/examples/R/body.tmpl` line 229 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX3yhl6g4fZanrDjfd:-NBX3yhl6g4fZanrDjfe:bimrzbo) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L229)):*
> ```
>     </li>
>     <li><a href="https://pmem.io/rpma/" target="_blank">https://pmem.io/rpma/</a>
>          - where you can find the librpma library manuals, configuration guidelines
> ```

. (lib... library)
___
*[`templates/examples/R/body.tmpl` line 234 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX43XH9pzGGesTfkh6:-NBX43XH9pzGGesTfkh7:bimrzbo) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L234)):*
> ```
>         <a href="https://www.intel.com/content/www/us/en/developer/articles/technical/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html" target="_blank">Persistent Memory Replication Over Traditional RDMA</a>.
>         <ul>
>             <li><b>Note</b> it describes RPMem in the context of the librpmem library
> ```

. (lib... library)
___
*[`templates/examples/R/body.tmpl` line 234 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX4Bmk22_xG2qF_AXW:-NBX4Bmk22_xG2qF_AXX:bjh8egs) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L234)):*
> ```
>         <a href="https://www.intel.com/content/www/us/en/developer/articles/technical/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html" target="_blank">Persistent Memory Replication Over Traditional RDMA</a>.
>         <ul>
>             <li><b>Note</b> it describes RPMem in the context of the librpmem library
> ```

perhaps mention that librpmem is now deprecated
___
*[`templates/examples/R/description.tmpl` line 15 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX4MiDEq2_qyJc_uBm:-NBX4MiDEq2_qyJc_uBn:bimrzbo) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/description.tmpl#L15)):*
> ```
> From this example you will learn how to establish an RDMA connection,
> prepare your local Persistent Memory for remote manipulation,
> and how to modify remote Persistent Memory using the librpma library.
> ```

. (lib... library)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)* status: 2 of 8 files reviewed, 15 unresolved discussions (waiting on @igchor, @ldorau, and @lukaszstolarczuk)

___
*[`docker/Dockerfile` line 35 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWs77Q1yfd4MlPfa6v:-NBXOE0n7NTtEfGQd_rF:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/docker/Dockerfile#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you please make these new deps as a sep. ENV (like RPMA_DEPS, e.g. https://github.com/pmem/rpma/blob/master/utils/docker/images/Dockerfile.fedora-33#L30)
</blockquote></details>

Done.



_Code quote:_
```Dockerfile
rdma-core-devel\
```
___
*[`docker/librpma.sh` line 4 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWsIcZ-pFzFr31CCvf:-NBXP1Se7EuCq0ay8oJJ:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/docker/librpma.sh#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can bump this to 1.1.0
</blockquote></details>

Done.
___
*[`docker/librpma.sh` line 7 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWsZSrA4pG8QLpxxQL:-NBXOupe11cjOC7XFB2A:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/docker/librpma.sh#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can drop this line and just use `pushd <...>` + `popd` (instead of `cd <...>` + `cd <back>`)
</blockquote></details>

Done.
___
*[`scripts/config_softroce.sh` line 3 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWt5rs-msGxfvQSdGt:-NBXP7Mi6iMWs373vAz5:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/scripts/config_softroce.sh#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`-2022`, I guess
</blockquote></details>

Done.
___
*[`templates/examples/R/body.tmpl` line 6 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWtpJR-nS5yoCNfxc8:-NBXPGlx31e5LZwzI5eg:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop "to you" perhaps (it sounds a little unnatural, for me)
</blockquote></details>

Done.



_Code quote:_
```
 this example we want to introduce to you a basic way of accessing the v
```
___
*[`templates/examples/R/body.tmpl` line 6 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWtuA4DEow3sK2tH0g:-NBXPk364H6AO8qQ6xvs:bnz9hfb) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`In this example,` (missing comma)
</blockquote></details>

Do you have a grammar rule for that? It seems unnatural for me.
___
*[`templates/examples/R/body.tmpl` line 7 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWv9s-BzT54zBdfpma:-NBXPgR-8gI1V48v4R8T:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop `it is`
</blockquote></details>

Done.



_Code quote:_
```
t Memory but when it is installed in a remote system. Remote P
```
___
*[`templates/examples/R/body.tmpl` line 15 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWyV7n233h1JaozhZ8:-NBXQCnuBQ3xYxfRlnAa:bb5lne5) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`rpma library` or `librpma`
</blockquote></details>

We use it in this way in the whole documentation of the librpma library: `the librpma library` or `librpma`.



_Code quote:_
```
the librpma library
```
___
*[`templates/examples/R/body.tmpl` line 59 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX-KfED8j7zt9peIz0:-NBXRgrQ4braswn3QkrQ:b-886gsx) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is this URL correct?
</blockquote></details>

Fixed



_Code quote:_
```
https://github.com/ldorau/2021-04-21.web/blob/devel/scripts/config_softroce.sh
```
___
*[`templates/examples/R/body.tmpl` line 198 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX38Qv6XeWBGSs_9nl:-NBXQMO_-nOAvzHOmwnj:b3kqx) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L198)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (lib... library)
</blockquote></details>

.
___
*[`templates/examples/R/body.tmpl` line 214 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX3efz7Zd2dQccfk3-:-NBXQa1e2aL-jEk-DYdL:b-t6nonw) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L214)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`incarnating` hmm... I'm not sure if this is a proper word...?
</blockquote></details>

implementing
___
*[`templates/examples/R/body.tmpl` line 229 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX3yhl6g4fZanrDjfd:-NBXQb4h7essjzSpM3N8:b3kqx) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L229)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (lib... library)
</blockquote></details>

.
___
*[`templates/examples/R/body.tmpl` line 234 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX43XH9pzGGesTfkh6:-NBXQcPd5RoTv3amsvEf:b3kqx) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L234)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (lib... library)
</blockquote></details>

.
___
*[`templates/examples/R/body.tmpl` line 234 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX4Bmk22_xG2qF_AXW:-NBXQrdn-dDeP16SlRRH:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L234)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps mention that librpmem is now deprecated
</blockquote></details>

Done.
___
*[`templates/examples/R/description.tmpl` line 15 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBX4MiDEq2_qyJc_uBm:-NBXQsuG-oPEzt-L9yZV:b3kqx) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/description.tmpl#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (lib... library)
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)* status: 2 of 8 files reviewed, 15 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`scripts/enable_pmemusers` line 97 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBTPzX33taiJw42bj0f:-NBXTHa-D8Qths3m0Si2:bk0qg8k) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/e4ff956b127ca39ddc1d213a04ba0229a97b1bb0/scripts/enable_pmemusers#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@ldorau, can you please file an issue for that, in this repo...?
</blockquote></details>

Done: https://github.com/pmemhackathon/hackathon.web/issues/5

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1: 

> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-:-NBXXV_s5JNggFXSzLGR:b-8fx2u7)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

___
*[`templates/examples/R/body.tmpl` line 6 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWtuA4DEow3sK2tH0g:-NBXWF2NAi8M7jizxgLE:b-wejw7v) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do you have a grammar rule for that? It seems unnatural for me.
</blockquote></details>

I usually follow this "introductory words" rule (see, e.g.: https://ell.stackexchange.com/a/243044), but I guess it can go either way
___
*[`templates/examples/R/body.tmpl` line 15 at r3](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBWyV7n233h1JaozhZ8:-NBXW_ri2uaVKGbwyxu5:b2zrrg5) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/a3fd71aa328b17770071563a899b936fbc380004/templates/examples/R/body.tmpl#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We use it in this way in the whole documentation of the librpma library: `the librpma library` or `librpma`.
</blockquote></details>

heh, we always try to reduce this 'redundancy' on pmem.io - I'll not enforce it here, though ;-)

**Review by ldorau — COMMENTED** [review]
Thanks @lukaszstolarczuk  :-)

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-:-NBXY4B379h1cQWwTS_K:b7nmv5y)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
@igchor, can you please take a look if this PR is alright with you and if it's building properly on the hackathon server (I didn't run one myself yet)

**Review by ldorau — COMMENTED** [review]
It's building and running properly on the hackathon server - I have checked :-)

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-:-NBXs4JD1EYVUePWulag:bs6ja4g)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

___
*[`scripts/enable_pmemusers` line 97 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-NBTPzX33taiJw42bj0f:-NBYAf2iAxQuHPZlgfqg:b-ucfknh) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/e4ff956b127ca39ddc1d213a04ba0229a97b1bb0/scripts/enable_pmemusers#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done: https://github.com/pmemhackathon/hackathon.web/issues/5
</blockquote></details>

Thanks!

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-:-NBYAsJTB_jE6sR3fqtl:bnfp4nl)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
@igchor Rebased

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/3#-:-NBYvi5h8zgg66tgv2rU:bxnxgwx)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

**Pull request merged**
