### PR TITLE
example F: update Web description

### PR DESCRIPTION
**Pull request by DamianDuy**
Matching updated code in: [pmemhackathon/hackathon#5](https://github.com/pmemhackathon/hackathon/pull/5)

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10)* status: all files reviewed, 3 unresolved discussions (waiting on @DamianDuy)

___
*[`templates/examples/F/body.tmpl` line 70 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-NCJr0cQ9S8uKwEEomAN:-NCJr0cQ9S8uKwEEomAO:bcinwz7) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/eecea3259bbef1da4fdf42d57b1eedc3727cf6cc/templates/examples/F/body.tmpl#L70)):*
> ```
> 
> <p>
> A simple C program using <b>libpmem2</b> is shown below. The correct machanism for flushing the data
> ```

`machanism` misspell
___
*[`templates/examples/F/body.tmpl` line 71 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-NCJrF_sBYewhAZyNAGs:-NCJrF_sBYewhAZyNAGt:b-o3xcnu) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/eecea3259bbef1da4fdf42d57b1eedc3727cf6cc/templates/examples/F/body.tmpl#L71)):*
> ```
> <p>
> A simple C program using <b>libpmem2</b> is shown below. The correct machanism for flushing the data
> into user storage is automatically chosen by <b>libpmem2</b>. To obtain the correct function for flushing
> ```

`user storage` -> `(underlaying) medium` (?)
___
*[`templates/examples/F/body.tmpl` line 74 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-NCJsnq73Z8NFduYbXPK:-NCJsnq73Z8NFduYbXPL:blnv7gi) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/eecea3259bbef1da4fdf42d57b1eedc3727cf6cc/templates/examples/F/body.tmpl#L74)):*
> ```
> from user space, <tt><a href="https://pmem.io/pmdk/manpages/linux/master/libpmem2/pmem2_get_persist_fn.3/" target="_new">pmem2_get_persist_fn()</a></tt>
> is used.
> <p>
> ```

perhaps we should describe here a little, when to call this function

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`templates/examples/F/body.tmpl` line 70 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-NCJr0cQ9S8uKwEEomAN:-NCdiVqx4MoCghmlKpdd:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/eecea3259bbef1da4fdf42d57b1eedc3727cf6cc/templates/examples/F/body.tmpl#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`machanism` misspell
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-:-NCdnyS369NkhCJfebZp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamianDuy)

**Review by wlemkows — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-:-NCtFdyBC5jo2N1G7rXA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamianDuy)

**Review by wlemkows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10)* status: all files reviewed, 1 unresolved discussion (waiting on @DamianDuy)

___
*[`templates/examples/F/body.tmpl` line 74 at r2](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-NCtGqFY2ARWWfd3vo3S:-NCtGqFY2ARWWfd3vo3T:b-bh2n4y) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/b105d45245bc895f38100c30bd10f5e6dc1a632e/templates/examples/F/body.tmpl#L74)):*
> ```
> from user space, <tt><a href="https://pmem.io/pmdk/manpages/linux/master/libpmem2/pmem2_get_persist_fn.3/" target="_new">pmem2_get_persist_fn()</a></tt>
> is used. It returns a pointer to the function, which efficiently persists the data in the range owned by the map. As can be seen in the example below,
> we call the obtained function with the provided <i>map</i> argument after our data was stored to the persistent memory (see line 93). The obtained function
> ```

I am not sure if those line numbers are correct (?)

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`templates/examples/F/body.tmpl` line 74 at r2](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-NCtGqFY2ARWWfd3vo3S:-NCtLM9Q3iIAVau6emb1:b-8qtmwk) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/b105d45245bc895f38100c30bd10f5e6dc1a632e/templates/examples/F/body.tmpl#L74)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

I am not sure if those line numbers are correct (?)
</blockquote></details>

I referred to the line where data was stored into memory instead of the line where the described `pmem2_get_persist_fn()` function was actually called, which was confusing. I've changed it now.

**Review by lukaszstolarczuk — APPROVED** [review]
:+1: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/10#-:-NCtt-Gm24qY45sUGx6T:b-8fx2u7)* status: all files reviewed, 1 unresolved discussion (waiting on @wlemkows)

**Pull request merged**
