### PR TITLE
Scripts for provisioning hackathon machines

### PR DESCRIPTION
**Pull request by igchor**
Authored-by lukaszx.lesniak@intel.com

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/2)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
@igchor, do you want to merge this one?
I'm assuming they might be some tweaks required/nice-to-have, but we could apply them later

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/2#-:-NBWqy4F02rs7UfQ-LwR:b-76hc0w)* status: 0 of 5 files reviewed, all discussions resolved

**Review by igchor — COMMENTED** [review]
Yes, I'd like to merge them. If someone from Romeo would have some time to add steps needed to configure Soft-RoCE that would be nice but it's  better to have something merged I think

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/2#-:-NBYAH9XBoY69EKhLxEA:b836px4)* status: 0 of 5 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@igchor I am afraid we do not have currently enough resources to work on that.
@grom72 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/2#-:-NBlTGKs0RaqAeQ1L_-3:b-7oa212)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/2)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
