### PR TITLE
common: docker/Dockerfile and scripts/README.md fixes and improvements

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
continuation of Janek's work (see original PR: https://github.com/pmemhackathon/2021-04-21.web/pull/6)

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

___
*[`docker/Dockerfile` line 4 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXUBGR50B3yoPnnlu5:-NBXUBGR50B3yoPnnlu6:bav495k) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/docker/Dockerfile#L4)):*
> ```Dockerfile
> # dockerfile for pmemhackathon, fc30 based
> #
> # Note: After making changes to files within this directory you have to rebuild
> ```

After having made changes ...



_Code quote:_
```Dockerfile
After making changes
```
___
*[`scripts/README.md` line 14 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXUtb7DVxw_SPY_c3k:-NBXUtb8Cjd3vVcl0HMm:b5mbe70) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L14)):*
> ```Markdown
> ```
> 
> **Note**: The command above copies part of the source tree to the hackathon home directory
> ```

`hackathon's`



_Code quote:_
```Markdown
hackathon
```
___
*[`scripts/README.md` line 28 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXVOiWBLEoxxuzzfoU:-NBXVOiWBLEoxxuzzfoV:bmz4cth) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L28)):*
> ```Markdown
> ```
> 
> 2. Create `/pmem0` and `/pmem1` mount points and provide them with DAX file system:
> ```

All other bullets start with a small letter ...



_Code quote:_
```Markdown
Create
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6)* status: all files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`scripts/README.md` line 47 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYGnOEs8caYZr8bRE:-NBXYGnOEs8caYZr8bRF:b-oq4rbn) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L47)):*
> ```Markdown
> ```
> 
> ## Foreach session with same users (or on system boot)
> ```

`For each`



_Code quote:_
```Markdown
Foreach
```
___
*[`scripts/README.md` line 63 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYQ_N2rAEJk6wYCzV:-NBXYQ_O8CPkcm4Fy87v:b-68snsv) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L63)):*
> ```Markdown
> ```
> 
> **Note**: In case of a failure, you can investigate the reason for that by analyzing the content of the `/home/hackathon/logs/` directory.
> ```

`the reason of that` ?



_Code quote:_
```Markdown
the reason for that
```
___
*[`scripts/README.md` line 73 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYbPWA9K0tezVBHjS:-NBXYbPWA9K0tezVBHjT:b1smf7d) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L73)):*
> ```Markdown
> ```
> 
> users can be disabled selectively using docker stop.
> ```

the `docker stop` command.



_Code quote:_
```Markdown
docker stop
```
___
*[`scripts/README.md` line 107 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYrh32ODxV6Cz56A3:-NBXYrh4CJsc0V5xQLZW:b-tn8nvl) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L107)):*
> ```Markdown
> ```
> 
> - `docker/*` please see the note within the `docker/Dockerfile` file
> ```

`in` ?



_Code quote:_
```Markdown
within 
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[`docker/Dockerfile` line 4 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXUBGR50B3yoPnnlu5:-NBXZ3au6egA6KBDvAB9:b-p3nbau) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/docker/Dockerfile#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

After having made changes ...
</blockquote></details>

I believe it's ok, I've made a small update
___
*[`scripts/README.md` line 14 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXUtb7DVxw_SPY_c3k:-NBXZ7XA0H-rTDH4zXlH:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`hackathon's`
</blockquote></details>

Done.
___
*[`scripts/README.md` line 28 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXVOiWBLEoxxuzzfoU:-NBXZ8Ma0zUv_6Z2sVeq:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All other bullets start with a small letter ...
</blockquote></details>

Done.
___
*[`scripts/README.md` line 47 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYGnOEs8caYZr8bRE:-NBXZAl88vKqDXjqpl1Z:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`For each`
</blockquote></details>

Done.
___
*[`scripts/README.md` line 63 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYQ_N2rAEJk6wYCzV:-NBXZFQT-W86hN8JmDqO:b28svpy) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the reason of that` ?
</blockquote></details>

Done, re-written.
___
*[`scripts/README.md` line 73 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYbPWA9K0tezVBHjS:-NBXZjCN5R8DNkPuGeN3:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the `docker stop` command.
</blockquote></details>

Done.
___
*[`scripts/README.md` line 107 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-NBXYrh32ODxV6Cz56A3:-NBXZygZ23re0uI6ng8J:b-ctuio1) ([raw file](https://github.com/pmemhackathon/hackathon.web/blob/3996732f80ab46babc7845b7cf4609b0245132e0/scripts/README.md#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`in` ?
</blockquote></details>

I guess both are correct, fixed anyway.

BTW, I moved it up, for clarity (I hope :smile: )

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon.web/6#-:-NBX_sW65pmtYirhVFEN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
